bookstore/bookstore1/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bookstore1.Models;


namespace bookstore1.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        
        public ActionResult Index()
        {
            ProductDBHandle dbhandle = new ProductDBHandle();
            ModelState.Clear();
            return View(dbhandle.GetProduct());

        }
        
        public ActionResult Dashboard()
        {
            return View();

        }

        // GET: Admin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Create
        
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        
        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create(Book bmodel)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    ProductDBHandle pdb = new ProductDBHandle();
                    if (pdb.AddProduct(bmodel))
                    {
                        ViewBag.Message = "Product Details Added Successfully";
                        ModelState.Clear();
                    }
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

    

    // GET: Admin/Edit/5
 
    public ActionResult Edit(int id)
        {

        ProductDBHandle pdb = new ProductDBHandle();
        return View(pdb.GetProduct().Find(bmodel => bmodel.Id == id));

    }

    // POST: Admin/Edit/5
    
    [HttpPost]
        public ActionResult Edit(int id, Book bmodel)
        {
            try
            {
                ProductDBHandle pdb = new ProductDBHandle();
                pdb.UpdateDetails(bmodel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }

        // GET: Admin/Delete/5

            
        public ActionResult Delete(int id)
        {
            try
            {
                ProductDBHandle pdb = new ProductDBHandle();
                if (pdb.DeleteProduct(id))
                {
                    ViewBag.AlertMsg = "Product Deleted Successfully";
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    


// POST: Admin/Delete/5

[HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        // POST: AdminSignUp/Create
        [HttpPost]
        [ActionName("Login")]
        public ActionResult Login(User admin)
        {
            try
            {
                // TODO: Add insert logic here


                UserDBHandle udb = new UserDBHandle();
                if (udb.validateAdmin(admin) == true)
                {
                   
                    ModelState.Clear();
                    Session["Firstname"] = admin.Firstname;
                    return View("Dashboard");
                    
                }
                else
                {
                    ViewBag.Message = "Restricted Access";
                    
                    ModelState.Clear();
                }

                return View();

            }
            catch
            {
                return View();
            }
        }
    }
}

bookstore/bookstore1/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bookstore1.Models;

namespace bookstore1.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }

        // GET: Cart/Details/5
        public ActionResult Details(int id)
        {
            ProductDBHandle productModel = new ProductDBHandle();
            productModel.GetProduct();
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                
                cart.Add(new Item { book = productModel.find(id), Quantity = 1 });
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item { book = productModel.find(id), Quantity = 1 });
                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Remove(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            int index = isExist(id);
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }
       


        // GET: Cart/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cart/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cart/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cart/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        private int isExist(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].book.Id.Equals(id))
                    return i;
            return -1;
        }

        // GET: Cart/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cart/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

bookstore/bookstore1/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bookstore1.Models;

namespace bookstore1.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            ProductDBHandle dbhandle = new ProductDBHandle();
            ModelState.Clear();
            return View(dbhandle.GetProduct());
            

        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            ProductDBHandle sdb = new ProductDBHandle();
            return View(sdb.GetProduct().Find(smodel => smodel.Id == id));

        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

bookstore/bookstore1/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bookstore1.Models;

namespace bookstore1.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Login()
        {
            return View();
        }

        // POST: Login/Create
        [HttpPost]
        
        public ActionResult Login(User loginUser)
        {
            try
            {
                // TODO: Add insert logic here


                UserDBHandle udb = new UserDBHandle();
                if (udb.validateUser(loginUser) == true)
                {

                    
                    ModelState.Clear();
                    return RedirectToAction("Create", "Payment");

                }
                else
                {
                    ViewBag.Message = "Invalid Credentials";

                }

                return View();

            }
            catch
            {
                return View();
            }
        }


        // GET: User/Create
        public ActionResult Register()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        [ActionName("Register")]
        public ActionResult Register(User user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UserDBHandle udb = new UserDBHandle();
                    if (udb.AddUser(user))
                    {
                        ViewBag.Message = "Your account has been created";
                        ModelState.Clear();
                    }
                }
                return View();
            }
            catch
            {
                return View();
            }

        }

        // GET: User/Edit/5
       
    }
}

bookstore/bookstore1/Views/Shared/Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/main.js"></script>

    <link href="~/Content/styles.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
          crossorigin="anonymous" />

</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="logo">
                    <h1><a href="#">DASHBOARD</a></h1>

                </div>
            </div>
            
        </div>

        <div class="row">

            <div class="col-md-12">
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">

                        <ul class="nav navbar-nav">
                            <li class="active"><a href="@Url.Action("Dashboard", "Admin")">Home</a></li>
                            <li><a href="@Url.Action("Index", "Admin")">Books</a></li>
                            <li><a href="#">Users</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            
                            <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                            
                        </ul>
                    </div>
                </nav>
            </div>

        </div>

        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-md-12 copyright">

                    <div class="col-md-6 col-sm-6 copyright-left">
                        <p>&copy; @DateTime.Now.Year - OnlineShopingStore. All right reserved.</p>
                    </div>

                    <div class="col-md-6 col-sm-6 copyright-right">

                        <ul class="list-unstyled list-social">
                            <li><a href="#" target="_blank"><i class="fab fa-facebook-square"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fab fa-google-plus"></i></a></li>

                        </ul>
                    </div>
                </div>
            </div>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/js")
    @RenderSection("scripts", required: false)
</body>
</html>

bookstore/bookstore1/Views/Shared/Dashboard.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/main.js"></script>

    <link href="~/Content/styles.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
          crossorigin="anonymous" />

</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="logo">
                    <h1><a href="#">DASHBOARD</a></h1>

                </div>
            </div>

        </div>

        <div class="row">

            <div class="col-md-12">
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">

                        <ul class="nav navbar-nav">
                            <li class="active"><a href="@Url.Action("Dashboard", "Admin")">Home</a></li>
                            <li><a href="@Url.Action("Index", "Admin")">Books</a></li>
                           
                        </ul>
                        <ul class="nav navbar-nav navbar-right">

                            <li><a href="@Url.Action("Login","Admin")"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>

                        </ul>
                    </div>
                </nav>
            </div>

        </div>

        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-md-12 copyright">

                    <div class="col-md-6 col-sm-6 copyright-left">
                        <p>&copy; @DateTime.Now.Year - OnlineShopingStore. All right reserved.</p>
                    </div>

                    <div class="col-md-6 col-sm-6 copyright-right">

                        <ul class="list-unstyled list-social">
                            <li><a href="#" target="_blank"><i class="fab fa-facebook-square"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fab fa-google-plus"></i></a></li>

                        </ul>
                    </div>
                </div>
            </div>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/js")
    @RenderSection("scripts", required: false)
</body>
</html>

bookstore/bookstore1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/Scripts/main.js"></script>



    <link href="~/Content/css.css" rel="stylesheet" />
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
          crossorigin="anonymous" />

</head>
<body>



    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6">
            <div class="logo">
                <h1><a href="#">READINGS</a></h1>

            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6">
            <div class="account">
                <ul>
                    <li>
                        <div class="hidden-xs">
                            <h4><a>Call</a></h4>
                            <p>010-#####-####</p>
                        </div>
                        <div class="visible-xs">
                            <p>0100-####-####</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <div class="row">

        <div class="col-md-12">

            <nav class="navbar navbar-inverse">
                <div class="container-fluid" style="margin:0;">

                    <ul class="nav navbar-nav">
                        <li class="active"><a href="@Url.Action("Index","Product")">Home</a></li>
                        <li><a href="@Url.Action("About","Home")">About</a></li>
                        <li><a href="@Url.Action("Contact","Home")">Contact</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Register","User")"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li><a href="@Url.Action("Login","User")"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                        <li><a href="@Url.Action("Index","Cart")"><i class="fas fa-shopping-cart"></i>Cart</a></li>
                    </ul>
                </div>
            </nav>
        </div>

    </div>

    @RenderBody()
    <hr />

    <footer>
        <div class="row copyright">
            <div class="col-sm-6 col-md-6 col-xs-6 copyright-left" style="margin-top:200px">
                <p>&copy; @DateTime.Now.Year - Readings. All right reserved.</p>
            </div>
            <div class="col-sm-6 col-md-6 col-xs-6 copyright-middle" >
                <h4 class="heading">Contacts</h4>
                <dl class="contact-list">
                    <dt>Address:</dt>
                    <dd>798 South Park Avenue, Jaipur, Raj</dd>
                </dl>
                <dl class="contact-list">
                    <dt>email:</dt>
                    <dd><a href="mailto:#">dkstudioin@gmail.com</a></dd>
                </dl>
                <dl class="contact-list">
                    <dt>phones:</dt>
                    <dd>
                        <a href="tel:#">https://karosearch.com</a> <span>or</span> <a href="tel:#">https://karosearch.com</a>
                    </dd>
                </dl>
            </div>

           
        </div>


    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/js")
    @RenderSection("scripts", required: false)

    <script>
        $(".show").click(function () {
            $(".error-message").show();
        });
    </script>
</body>
</html>